#
# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM ubuntu:18.04 

RUN apt-get update && apt-get install -y --no-install-recommends openjdk-8-jdk openjdk-8-jre scala python python-pip python3 python3-pip bc
RUN rm -r /usr/lib/python*/ensurepip && \
    pip install --upgrade pip setuptools && \
    rm -r /root/.cache && rm -rf /var/cache/apt/*

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-amd64
ENV PATH $PATH:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin

# Before building the docker image, first either download Apache Spark 3.0+ from 
# http://spark.apache.org/downloads.html or build and make a Spark distribution following
# the instructions in http://spark.apache.org/docs/3.0.1/building-spark.html (3.0.0 can 
# be used as well).  
# If this docker file is being used in the context of building your images from a Spark
# distribution, the docker build command should be invoked from the top level directory
# of the Spark distribution. E.g.:
# docker build -t spark:3.0.1 -f kubernetes/dockerfiles/spark/Dockerfile .

RUN set -ex && \
    ln -s /lib /lib64 && \
    mkdir -p /opt/spark && \
    mkdir -p /opt/spark/logs && \
    mkdir -p /opt/spark/conf && \
    mkdir -p /opt/spark/jars && \
    mkdir -p /opt/tpch && \
    mkdir -p /opt/spark/work && \
    mkdir -p /opt/sparkRapidsPlugin && \
    touch /opt/spark/RELEASE && \
    rm /bin/sh && \
    ln -sv /bin/bash /bin/sh && \
    echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
    chgrp root /etc/passwd && chmod ug+rw /etc/passwd

RUN mkdir /opt/spark/python
RUN mkdir /opt/criteo
RUN chmod g+w /opt/criteo
RUN mkdir -p /opt/sparkRapidsPlugin

COPY spark/jars /opt/spark/jars
COPY spark/bin /opt/spark/bin
COPY spark/sbin /opt/spark/sbin
COPY spark/data /opt/spark/data
COPY spark/python/pyspark /opt/spark/python/pyspark
COPY spark/python/lib /opt/spark/python/lib

COPY sparkRapidsPlugin/cudf-0.16-cuda11.jar /opt/sparkRapidsPlugin
COPY sparkRapidsPlugin/rapids-4-spark_2.12-0.4.0-20201202.065456-3.jar /opt/sparkRapidsPlugin
COPY sparkRapidsPlugin/getGpusResources.sh /opt/sparkRapidsPlugin

COPY criteo/xgboost4j-spark_3.0-1.3.0-20201202.095320-95.jar /opt/criteo
COPY criteo/xgboost4j_3.0-1.3.0-20201202.095259-95.jar /opt/criteo
COPY criteo/sample_xgboost_apps-0.2.2-20201009.130638-4.jar /opt/criteo
COPY criteo/spark_data_utils.py /opt/criteo

ENV CRITEO_HOME /opt/criteo
ENV SPARK_HOME /opt/spark

ENV CUDF_JAR_NAME cudf-0.16-cuda11.jar
ENV RAPIDS_JAR_NAME rapids-4-spark_2.12-0.4.0-20201202.065456-3.jar

ENV XGBOOST_SPARK_JAR_NAME xgboost4j-spark_3.0-1.3.0-20201202.095320-95.jar
ENV XGBOOST_JAR_NAME xgboost4j_3.0-1.3.0-20201202.095259-95.jar

ENV SPARK_RAPIDS_DIR /opt/sparkRapidsPlugin
ENV SPARK_CUDF_JAR $SPARK_RAPIDS_DIR/$CUDF_JAR_NAME
ENV SPARK_RAPIDS_PLUGIN_JAR=$SPARK_RAPIDS_DIR/$RAPIDS_JAR_NAME

ENV XGBOOST_JAR ${CRITEO_HOME}/${XGBOOST_JAR_NAME}
ENV XGBOOST_SPARK_JAR ${CRITEO_HOME}/${XGBOOST_SPARK_JAR_NAME}
ENV JARS ${XGBOOST_JAR},${XGBOOST_SPARK_JAR},${SPARK_RAPIDS_PLUGIN_JAR},${SPARK_CUDF_JAR}

WORKDIR /opt/spark/work
RUN chmod g+w /opt/spark/work

ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master
